### ISSUE TITLE
Create simulated STRs

### ISSUE THREAD

**Issue by wdecoster** [collaborativebioinformatics/STRdust#1]
Depends on https://github.com/collaborativebioinformatics/STR_Integration/issues/2

**Comment by DamarisLa** [comment]
python ./simulator7.3.py "REFERENCE.fa" "./manipulated/OUTPUT.fa" "../bedfiles/SORTED_INPUT.bed" "./manipulated/OUTPUT.bed" 0.50 "d" 0.01 10 0.30

Explanation of this example:
0.50 numbers of given regions that should be manipulated
"d" for diploid changes : else "h"
0.01 => 1% SNV-mutations added to the STR-regions 
10 => 10x rarer is a insertion or deletions (compared to the mutations) 
0.30 => 30% homozygous regions rest is heterozygous change to STR-regions
