### ISSUE TITLE
Add mreps to check repetiviness (is that a word?) of consensus sequence

### ISSUE THREAD

**Issue by wdecoster** [collaborativebioinformatics/STRdust#16]

**Comment by Fu-Yilei** [comment]
The consensus sequences are the return from function create_consensus? I can add this function into the code and push to my branch after that.

**Comment by wdecoster** [comment]
Yes, that would be an okay place to investigate what exactly the sequence is that we created the consensus from.
Please keep in mind that, while I did not just make parameters for the spoa up, these may need to be evaluated to see if these yield the best result.

Then we want to know if a sequence is actually repetitive and what the nucleotide motif is. mreps is pretty fast :-)
